<?php

declare(strict_types=1);

namespace Turnmark\Scraper\Tests\Scrapers;

use Carbon\CarbonImmutable as Carbon;

/**
 * @psalm-import-type Arguments from \Turnmark\Scraper\Tests\ScraperPsalmType
 * @psalm-import-type Expected from \Turnmark\Scraper\Tests\ScraperPsalmType
 *
 * @author shimomo
 */
final class ProgramScraperDataProvider
{
    /**
     * @return non-empty-list<
     *     array{
     *         arguments: Arguments,
     *         expected: Expected,
     *     }
     * >
     */
    public static function scrapeProvider(): array
    {
        return [
            [
                'arguments' => [Carbon::parse('2026-05-31'), 6, 12],
                'expected' => [
                    'date' => '2026-05-31',
                    'stadium_number' => 6,
                    'race_number' => 12,
                    'closed_at' => '2026-05-31 16:35:00',
                    'grade_number_source' => 'SGa',
                    'grade_number' => 100,
                    'title' => '第53回ボートレースオールスター',
                    'subtitle' => '優勝戦',
                    'distance_source' => '1800m',
                    'distance' => 1800,
                    'day_number_source' => '最終日',
                    'day_number' => 6,
                    'racers' => [
                        1 => [
                            'entry_number' => 1,
                            'name' => '丸野 一樹',
                            'number' => 4686,
                            'rank_number_source' => 'A1',
                            'rank_number' => 1,
                            'branch_number_source' => '滋賀',
                            'branch_number' => 25,
                            'birthplace_number_source' => '京都',
                            'birthplace_number' => 26,
                            'age_source' => '34歳',
                            'age' => 34,
                            'weight_source' => '52.0kg',
                            'weight' => 52.0,
                            'flying_count_source' => 'F0',
                            'flying_count' => 0,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.15,
                            'national_top_1_percent' => 6.7,
                            'national_top_2_percent' => 42.02,
                            'national_top_3_percent' => 58.82,
                            'local_top_1_percent' => 7.71,
                            'local_top_2_percent' => 58.82,
                            'local_top_3_percent' => 70.59,
                            'motor_number' => 23,
                            'motor_top_2_percent' => 26.92,
                            'motor_top_3_percent' => 38.46,
                            'boat_number' => 45,
                            'boat_top_2_percent' => 40.41,
                            'boat_top_3_percent' => 52.74,
                        ],
                        2 => [
                            'entry_number' => 2,
                            'name' => '定松 勇樹',
                            'number' => 5121,
                            'rank_number_source' => 'A1',
                            'rank_number' => 1,
                            'branch_number_source' => '佐賀',
                            'branch_number' => 41,
                            'birthplace_number_source' => '福岡',
                            'birthplace_number' => 40,
                            'age_source' => '25歳',
                            'age' => 25,
                            'weight_source' => '52.0kg',
                            'weight' => 52.0,
                            'flying_count_source' => 'F0',
                            'flying_count' => 0,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.14,
                            'national_top_1_percent' => 7.93,
                            'national_top_2_percent' => 63.85,
                            'national_top_3_percent' => 75.38,
                            'local_top_1_percent' => 7.4,
                            'local_top_2_percent' => 60.0,
                            'local_top_3_percent' => 70.0,
                            'motor_number' => 61,
                            'motor_top_2_percent' => 26.92,
                            'motor_top_3_percent' => 57.69,
                            'boat_number' => 76,
                            'boat_top_2_percent' => 36.42,
                            'boat_top_3_percent' => 49.01,
                        ],
                        3 => [
                            'entry_number' => 3,
                            'name' => '上野 真之介',
                            'number' => 4503,
                            'rank_number_source' => 'A1',
                            'rank_number' => 1,
                            'branch_number_source' => '佐賀',
                            'branch_number' => 41,
                            'birthplace_number_source' => '佐賀',
                            'birthplace_number' => 41,
                            'age_source' => '38歳',
                            'age' => 38,
                            'weight_source' => '52.0kg',
                            'weight' => 52.0,
                            'flying_count_source' => 'F0',
                            'flying_count' => 0,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.12,
                            'national_top_1_percent' => 7.68,
                            'national_top_2_percent' => 60.83,
                            'national_top_3_percent' => 72.5,
                            'local_top_1_percent' => 8.62,
                            'local_top_2_percent' => 73.08,
                            'local_top_3_percent' => 84.62,
                            'motor_number' => 3,
                            'motor_top_2_percent' => 66.67,
                            'motor_top_3_percent' => 66.67,
                            'boat_number' => 15,
                            'boat_top_2_percent' => 35.14,
                            'boat_top_3_percent' => 50.68,
                        ],
                        4 => [
                            'entry_number' => 4,
                            'name' => '山田 康二',
                            'number' => 4500,
                            'rank_number_source' => 'A1',
                            'rank_number' => 1,
                            'branch_number_source' => '佐賀',
                            'branch_number' => 41,
                            'birthplace_number_source' => '佐賀',
                            'birthplace_number' => 41,
                            'age_source' => '38歳',
                            'age' => 38,
                            'weight_source' => '52.0kg',
                            'weight' => 52.0,
                            'flying_count_source' => 'F0',
                            'flying_count' => 0,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.12,
                            'national_top_1_percent' => 7.5,
                            'national_top_2_percent' => 49.59,
                            'national_top_3_percent' => 71.54,
                            'local_top_1_percent' => 8.06,
                            'local_top_2_percent' => 64.71,
                            'local_top_3_percent' => 82.35,
                            'motor_number' => 2,
                            'motor_top_2_percent' => 44.0,
                            'motor_top_3_percent' => 60.0,
                            'boat_number' => 31,
                            'boat_top_2_percent' => 27.34,
                            'boat_top_3_percent' => 48.2,
                        ],
                        5 => [
                            'entry_number' => 5,
                            'name' => '新田 雄史',
                            'number' => 4344,
                            'rank_number_source' => 'A1',
                            'rank_number' => 1,
                            'branch_number_source' => '三重',
                            'branch_number' => 24,
                            'birthplace_number_source' => '三重',
                            'birthplace_number' => 24,
                            'age_source' => '41歳',
                            'age' => 41,
                            'weight_source' => '52.2kg',
                            'weight' => 52.2,
                            'flying_count_source' => 'F0',
                            'flying_count' => 0,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.12,
                            'national_top_1_percent' => 7.44,
                            'national_top_2_percent' => 47.22,
                            'national_top_3_percent' => 70.37,
                            'local_top_1_percent' => 7.91,
                            'local_top_2_percent' => 72.73,
                            'local_top_3_percent' => 90.91,
                            'motor_number' => 1,
                            'motor_top_2_percent' => 20.59,
                            'motor_top_3_percent' => 38.24,
                            'boat_number' => 12,
                            'boat_top_2_percent' => 33.77,
                            'boat_top_3_percent' => 48.34,
                        ],
                        6 => [
                            'entry_number' => 6,
                            'name' => '佐藤 翼',
                            'number' => 4573,
                            'rank_number_source' => 'A1',
                            'rank_number' => 1,
                            'branch_number_source' => '埼玉',
                            'branch_number' => 11,
                            'birthplace_number_source' => '埼玉',
                            'birthplace_number' => 11,
                            'age_source' => '37歳',
                            'age' => 37,
                            'weight_source' => '52.0kg',
                            'weight' => 52.0,
                            'flying_count_source' => 'F1',
                            'flying_count' => 1,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.13,
                            'national_top_1_percent' => 6.77,
                            'national_top_2_percent' => 41.88,
                            'national_top_3_percent' => 61.54,
                            'local_top_1_percent' => 5.53,
                            'local_top_2_percent' => 29.41,
                            'local_top_3_percent' => 41.18,
                            'motor_number' => 62,
                            'motor_top_2_percent' => 45.45,
                            'motor_top_3_percent' => 59.09,
                            'boat_number' => 43,
                            'boat_top_2_percent' => 29.37,
                            'boat_top_3_percent' => 50.0,
                        ],
                    ],
                ],
            ],
            [
                'arguments' => [Carbon::parse('2026-05-18'), 13, 12],
                'expected' => [
                    'date' => '2026-05-18',
                    'stadium_number' => 13,
                    'race_number' => 12,
                    'closed_at' => null,
                    'grade_number_source' => null,
                    'grade_number' => null,
                    'title' => null,
                    'subtitle' => null,
                    'distance_source' => null,
                    'distance' => null,
                    'day_number_source' => null,
                    'day_number' => null,
                    'racers' => [],
                ],
            ],
        ];
    }
}
