name: Split

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  split:
    name: Split ${{ matrix.package }} (Ubuntu 24.04)
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package:
          - scraper
          - scraper-fukuoka
          - scraper-tokuyama
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.TURNMARK_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Split and Push ${{ matrix.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.TURNMARK_ACCESS_TOKEN }}
        uses: danharrin/monorepo-split-github-action@v2.4.0
        with:
          package_directory: packages/${{ matrix.package }}
          repository_organization: turnmark
          repository_name: ${{ matrix.package }}
          branch: main
          tag: ${{ github.ref_name }}
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
